### NumPy

### 1D Array

In [1]:
import numpy as np

In [2]:
a1 = np.array([10.5, 13.6, 11, 44,67.8])
type(a1)

numpy.ndarray

In [4]:
a1

array([10.5, 13.6, 11. , 44. , 67.8])

In [3]:
a1.ndim
a1.shape

(5,)

### 2D Array

In [5]:
b2 = [[1, 2, 3, 4],
      [5, 6, 7, 8]]
type(b2)

list

In [6]:
c2 = np.array(b2)
type(c2)

numpy.ndarray

In [7]:
c2.ndim

2

In [8]:
c2.shape

(2, 4)

### 3D Array

In [9]:
b3 = [[[1,2,3,4],
       [5,6,7,8]],
      
       [[9,10,11,12],
       [13,14,15,16]],
       
       [[11,22,33,44],
       [55,666,77,88]]]
type(b3)


list

In [10]:
c3 = np.array(b3)
print(c3)

[[[  1   2   3   4]
  [  5   6   7   8]]

 [[  9  10  11  12]
  [ 13  14  15  16]]

 [[ 11  22  33  44]
  [ 55 666  77  88]]]


In [11]:
c3.ndim

3

In [12]:
c3.shape

(3, 2, 4)

### why numpy array is used instead of list

In [13]:
a = [4,5,6,7,8]
type(a)

list

In [14]:
a*3

[4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8]

In [15]:
a1 = []

for i in a:
    a1.append(i*3)

In [16]:
a

[4, 5, 6, 7, 8]

In [17]:
a1

[12, 15, 18, 21, 24]

In [18]:
c = np.array(a)
c

array([4, 5, 6, 7, 8])

In [19]:
d = 3*c

In [20]:
d

array([12, 15, 18, 21, 24])

In [21]:
c**(1/2)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712])

### get the product of all the no. in list

In [22]:
e = [2, 3, 11, 12, 13]
type(e)

list

In [23]:
# intialise the product to 1

p = 1

# apply for loop
for i in e:
    p = p * i
    

In [24]:
p

10296

In [25]:
np.prod(e)

np.int64(10296)

In [26]:
np.sum(e)

np.int64(41)

In [28]:
np.mean(e)

np.float64(8.2)

In [29]:
np.median(e)

np.float64(11.0)

In [30]:
np.min(e)

np.int64(2)

In [31]:
np.prod(e)

np.int64(10296)

### Mathematical functions in numpy
1. exp
2. log
3. sin
4. cos
5. tan
6. 1rad = pi/180 deg


In [36]:
np.exp(1)

np.float64(2.718281828459045)

In [32]:
a = [[1,2,3],
     [4,5,6]]
type(a)

list

In [34]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [35]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [37]:
b = [0, 30, 45, 60, 90]
c = np.radians(b)

In [38]:
c

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [39]:
np.sin(c)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [40]:
np.cos(c).round(4)

array([1.    , 0.866 , 0.7071, 0.5   , 0.    ])

In [41]:
np.tan(c).round(4)

array([0.00000000e+00, 5.77400000e-01, 1.00000000e+00, 1.73210000e+00,
       1.63312394e+16])